services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=nodejs_ref_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

